[package]
name = "neuralr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "dylib"]

[dependencies]
pyo3 = { version = "0.23.4", optional = true }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
pyo3 = { version = "*" }
